export enum EnvVar {
  DB_HOST = "DB_HOST",
  DB_USER = "DB_USER",
  DB_PASSWORD = "DB_PASSWORD",
  DB_NAME = "DB_NAME",
  DB_PORT = "DB_PORT",

  PIHOLE_HOST = "PIHOLE_HOST",
  PIHOLE_REMOTE_DB_PATH = "PIHOLE_REMOTE_DB_PATH",
  PIHOLE_REMOTE_BACKUP_FOLDER = "PIHOLE_REMOTE_BACKUP_FOLDER",
  PIHOLE_DOCKER_CONTAINER_NAME = "PIHOLE_DOCKER_CONTAINER_NAME",
  PIHOLE_LOCAL_BACKUP_FOLDER = "PIHOLE_LOCAL_BACKUP_FOLDER",

  LOCATIONS_HOST = "LOCATIONS_HOST",
  LOCATIONS_REMOTE_DB_PATH = "LOCATIONS_REMOTE_DB_PATH",
  LOCATIONS_REMOTE_BACKUP_FOLDER = "LOCATIONS_REMOTE_BACKUP_FOLDER",
  LOCATIONS_LOCAL_BACKUP_FOLDER = "LOCATIONS_LOCAL_BACKUP_FOLDER",

  OBSIDIAN_FOLDER = "OBSIDIAN_FOLDER",
  OBSIDIAN_IGNORE_FOLDERS = "OBSIDIAN_IGNORE_FOLDERS",

  TIMEZONE = "TIMEZONE",

  PRIVATE_KEY_PATH = "PRIVATE_KEY_PATH",
  SAMSUNG_HEALTH_FOLDER = "SAMSUNG_HEALTH_FOLDER",

  GOOGLE_TAKEOUT_RECORDS_JSON = "GOOGLE_TAKEOUT_RECORDS_JSON",
  GOOGLE_LOCATIONS_EXPORT_JSON = "GOOGLE_LOCATIONS_EXPORT_JSON",

  OWNTRACKS_HTTP_SERVER = "OWNTRACKS_HTTP_SERVER",

  HARES_JSON_FILE_PATH = "HARES_JSON_FILE_PATH",
  OBSIDIAN_HABITS_SNAPSHOT_FILE_PATH = "OBSIDIAN_HABITS_SNAPSHOT_FILE_PATH",

  S3_ACCESS_KEY_ID = "S3_ACCESS_KEY_ID",
  S3_SECRET_ACCESS_KEY = "S3_SECRET_ACCESS_KEY",
  S3_REGION = "S3_REGION",
  S3_SERVER_URL = "S3_SERVER_URL",

  AMQP_URL = "AMQP_URL",

  INGESTER_QUEUE_NAME = "INGESTER_QUEUE_NAME",
}

export function getEnvVarOrError(name: EnvVar) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} env var is required`);
  }
  return value;
}
